### ISSUE TITLE
Error 1d atomic vector

### ISSUE THREAD

**Issue by PMassicotte** [dgrtwo/fuzzyjoin#2]
I wanted to give a try to this package but this error came up.

``` r
df1 <-
  structure(
  list(
  lake = c(
  "McCullough",
  "McCullough",
  "Partridge",
  "Randall",
  "Tomahawk",
  "Ward",
  "White Sand",
  "Allequash",
  "Island",
  "Katinka"
  )
  ),
  .Names = "lake",
  class = c("tbl_df", "data.frame"),
  row.names = c(NA, -10L)
  )
  
  df2 <-
  structure(
  list(
  lakename = c(
  "Allequash Lake",
  "Anvil Lake",
  "Arrowhead Lake",
  "Bass Lake",
  "Big Lake",
  "Birch Lake",
  "Ballard Lake",
  "Big Muskellunge Lake",
  "Black Oak Lake",
  "Big Portage Lake"
  )
  ),
  .Names = "lakename",
  class = c("tbl_df",
  "data.frame"),
  row.names = c(NA, -10L)
  )
  names(df1)
```

    ## [1] "lake"

``` r
  names(df2)
```

    ## [1] "lakename"

``` r
  stringdist_left_join(df1,  df2,   by = c("lake" = "lakename"),  max_dist = 1)
```

    ## Error: data_frames can only contain 1d atomic vectors and lists

Any idea?

Thank you

**Comment by dgrtwo** [comment]
Thanks for the report! This gave an error because it had no (fuzzy) matches between the two columns, and I hadn't handled that situation properly. It does now, such that your code returns only NAs in the lakename column.

The reason it doesn't have any matches is that you have " Lake" at the end of each `lakename` string, which makes it at least a distance of 5 away from any `lake`. You could fix this just by any of the following options:

1. Removing the ` Lake` from each string (the non-fuzzyjoin solution)

2. Match on cases where `lakename` *contains* `lake` using `regex_join`:

    regex_right_join(df2, df1, by = c("lakename" = "lake"))

(Note that as of now `regex_right_join` always needs to have the regex column in the second argument, thus I needed to switch their order)

3. Switch to using soundex distance, which has a knack for finding matches even with an extra word (note that soundex returns 0 or 1 so you need to change max_dist to 5):

    stringdist_left_join(df1,  df2,   by = c("lake" = "lakename"),  max_dist = .5, method = "soundex")

**Comment by PMassicotte** [comment]
Thank you very much for your time!
